name: Build and Deploy Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Install Migrate Tool
      run: |
        curl -L https://github.com/golang-migrate/migrate/releases/download/v4.x.x/migrate.linux-amd64.tar.gz | tar xvz
        sudo mv migrate.linux-amd64 /usr/local/bin/migrate

    - name: Build and push Docker image
      run: |
        docker build -t georhugaev/survey-app:latest .
        migrate -path db/migration -database "postgresql://gen_user:%7B%3CPZ*m7%3Clu%2B24e@94.241.138.220:5432/survey_db" up
        docker push georhugaev/survey-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          docker stop $(docker ps -aq) || true 
          docker rm $(docker ps -aq) || true 
          docker image prune -af
          docker pull georhugaev/survey-app:latest 
          docker run -d -p 8091:8091 --name survey-app georhugaev/survey-app:latest 
